#!/bin/bash
# Running wrapper to prepare config
nohup /usr/local/bin/wrapper &>/dev/null &
# Capture wrapper pid
last_pid=$!
# Sleep for 120 secs (for config to complete)
sleep 180
# seed db
echo yes | /usr/bin/gitlab-rake gitlab:setup
# remove process tree
/usr/local/bin/killtree $last_pid KILL

