---
services:
  gitlab:
    git_url: git://github.com/cloud66-samples/gitlab
    git_branch: master
    build_command: seeder
    ports:
    - container: 80
      http: 80
      https: 443
    - container: 22
      tcp: 10022
    volumes:
    - "/var/gitlab/data:/var/opt/gitlab"
    - "/var/gitlab/logs:/var/log/gitlab"
    - "/var/gitlab/configurations:/etc/gitlab"
    health:
      type: normal
      endpoint: "/users/sign_in"
      protocol: http
      timeout: 300s
      accept:
      - '200'
      - 300-399
databases:
- postgresql
- redis
